package com.amplify.posttask.entity;

import java.util.Date;
import java.util.Map;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.DynamoDBAttributeType;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedJson;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTyped;
import com.amplify.posttask.enums.PostTaskActivityEnum;
import com.amplify.posttask.enums.PostTaskCategoryEnum;
import com.amplify.posttask.enums.PostTaskTargetPlatformEnum;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Builder
@AllArgsConstructor
@NoArgsConstructor
@Data
@Getter
@DynamoDBTable(tableName = "post_task")
public class PostTask {

    @DynamoDBHashKey
	  @DynamoDBAutoGeneratedKey
	  private String postTaskId;

    @DynamoDBAttribute
    private String targetPlatformPostUrl;
    
    @DynamoDBAttribute
    private String content;

    @DynamoDBTyped(DynamoDBAttributeType.BOOL)
    private Boolean isSuggestedPost;

    @DynamoDBTyped(DynamoDBAttributeType.BOOL)
    private Boolean isPriorityPost;

    @DynamoDBTypeConvertedEnum
    private PostTaskCategoryEnum postTaskCategory;

    @DynamoDBTypeConvertedEnum
    private PostTaskTargetPlatformEnum postTaskTargetPlatform;

    @DynamoDBTypeConvertedJson
    private Map<String, Integer> points;

    @DynamoDBAttribute
    private Date expirationTS;
    
    // @DynamoDBAutoGeneratedTimestamp
    // private Timestamp createdTS;

    // @DynamoDBTypeConvertedTimestamp
    // private Timestamp updatedTS;     

}
